repos:
  # General formatting and cleanup
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-json
      - id: check-toml

  # Python formatting and linting
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        files: ^apps/iot-supervisor-app/
        language_version: python3.11

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.10
    hooks:
      - id: ruff
        args: [--fix]
        files: ^apps/iot-supervisor-app/

  # TypeScript/JavaScript formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        files: \.(js|ts|jsx|tsx|json|css|md|yaml|yml)$
        exclude: ^(apps/iot-supervisor-app/|packages/bms-schemas/python/|packages/bms-schemas/typescript/|packages/bms-schemas/json-schema/)

  # Local schema validation
  - repo: local
    hooks:
      - id: schema-test
        name: Run schema tests
        entry: bash -c 'cd packages/bms-schemas && npm run test'
        language: system
        files: ^packages/bms-schemas/src/
        pass_filenames: false
