// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client'
import { client } from './client.gen'
import type {
  GetTemplatesApiV1223pTemplatesGetData,
  GetTemplatesApiV1223pTemplatesGetErrors,
  GetTemplatesApiV1223pTemplatesGetResponses,
  HealthCheckHealthGetData,
  HealthCheckHealthGetResponses,
} from './types.gen'

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>
}

/**
 * Get all ASHRAE 223P templates with hierarchical structure
 *
 * Retrieve complete template hierarchy with systems, devices, properties, and space types with all relationships embedded. No separate lookups needed - everything in one response.
 */
export const getTemplatesApiV1223pTemplatesGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetTemplatesApiV1223pTemplatesGetData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    GetTemplatesApiV1223pTemplatesGetResponses,
    GetTemplatesApiV1223pTemplatesGetErrors,
    ThrowOnError
  >({
    url: '/api/v1/223p/templates',
    ...options,
  })
}

/**
 * Health Check
 *
 * Health check endpoint.
 */
export const healthCheckHealthGet = <ThrowOnError extends boolean = false>(
  options?: Options<HealthCheckHealthGetData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    HealthCheckHealthGetResponses,
    unknown,
    ThrowOnError
  >({
    url: '/health',
    ...options,
  })
}
