// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}/building-semantics` | (string & {})
}

/**
 * DeviceType
 *
 * Device type enum for UI behavior.
 */
export type DeviceType = 'sensor' | 'other'

/**
 * SpaceTypeDTO
 *
 * Space type template from ASHRAE 223P ontology.
 */
export type SpaceTypeDto = {
  /**
   * Id
   *
   * Space type URN
   */
  id: string
  /**
   * Label
   *
   * Human-readable label
   */
  label: string
  /**
   * Description
   *
   * Space type description
   */
  description?: string | null
}

/**
 * TemplateDeviceDTO
 *
 * Device type template with nested properties and UI metadata.
 */
export type TemplateDeviceDto = {
  /**
   * Id
   *
   * Template name (e.g., 'damper')
   */
  id: string
  /**
   * Label
   *
   * Human-readable label
   */
  label: string
  /**
   * Classuri
   *
   * ASHRAE 223P class URI
   */
  classUri: string
  /**
   * Device type for UI behavior (sensor vs other)
   */
  deviceType: DeviceType
  /**
   * Description
   *
   * Device description
   */
  description?: string | null
  /**
   * Properties
   *
   * Valid properties for this device
   */
  properties: Array<TemplatePropertyDto>
}

/**
 * TemplatePropertyDTO
 *
 * Observable property template with hierarchical nesting and metadata.
 */
export type TemplatePropertyDto = {
  /**
   * Id
   *
   * Template name (e.g., 'water-temperature')
   */
  id: string
  /**
   * Label
   *
   * Human-readable label
   */
  label: string
  /**
   * Classuri
   *
   * ASHRAE 223P class URI
   */
  classUri: string
  /**
   * Propertytype
   *
   * Property type
   */
  propertyType: 'quantifiable' | 'enumerated'
  /**
   * Quantitykind
   *
   * QUDT quantity kind (e.g., 'Temperature', 'Pressure')
   */
  quantityKind?: string | null
  /**
   * Unit
   *
   * QUDT unit (e.g., 'DEG_C', 'PSI')
   */
  unit?: string | null
  /**
   * Medium
   *
   * s223 medium (e.g., 'Water', 'Air') - optional
   */
  medium?: string | null
  /**
   * Enumerationkind
   *
   * s223 enumeration kind (e.g., 'RunStatus') - only for enumerated properties
   */
  enumerationKind?: string | null
  /**
   * Isactuatable
   *
   * Observable (false) vs Actuatable (true)
   */
  isActuatable: boolean
  /**
   * Description
   *
   * Property description
   */
  description?: string | null
}

/**
 * TemplateSystemDTO
 *
 * System (equipment) type template with nested devices and class URI.
 */
export type TemplateSystemDto = {
  /**
   * Id
   *
   * Template name (e.g., 'vav-reheat')
   */
  id: string
  /**
   * Label
   *
   * Human-readable label
   */
  label: string
  /**
   * Classuri
   *
   * ASHRAE 223P class URI
   */
  classUri: string
  /**
   * Description
   *
   * System description
   */
  description?: string | null
  /**
   * Devices
   *
   * Valid devices for this system
   */
  devices: Array<TemplateDeviceDto>
}

/**
 * TemplatesResponseDTO
 *
 * Complete hierarchical template structure with all relationships.
 */
export type TemplatesResponseDto = {
  /**
   * Systems
   *
   * All ASHRAE 223P system templates with nested devices and properties
   */
  systems: Array<TemplateSystemDto>
  /**
   * Spacetypes
   *
   * All ASHRAE 223P space type templates
   */
  spaceTypes: Array<SpaceTypeDto>
}

export type GetTemplatesApiV1223pTemplatesGetData = {
  body?: never
  path?: never
  query?: never
  url: '/api/v1/223p/templates'
}

export type GetTemplatesApiV1223pTemplatesGetErrors = {
  /**
   * Internal server error
   */
  500: unknown
}

export type GetTemplatesApiV1223pTemplatesGetResponses = {
  /**
   * Complete template structure
   */
  200: TemplatesResponseDto
}

export type GetTemplatesApiV1223pTemplatesGetResponse =
  GetTemplatesApiV1223pTemplatesGetResponses[keyof GetTemplatesApiV1223pTemplatesGetResponses]

export type HealthCheckHealthGetData = {
  body?: never
  path?: never
  query?: never
  url: '/health'
}

export type HealthCheckHealthGetResponses = {
  /**
   * Response Health Check Health Get
   *
   * Successful Response
   */
  200: {
    [key: string]: string
  }
}

export type HealthCheckHealthGetResponse =
  HealthCheckHealthGetResponses[keyof HealthCheckHealthGetResponses]
