
"""add control sequence instances table

Revision ID: 893fe7d2dc9b
Revises:
Create Date: 2025-12-09 11:59:54.922670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '893fe7d2dc9b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('control_sequence_instances',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('instance_id', sa.String(length=255), nullable=False),
    sa.Column('sequence_type', sa.String(length=50), nullable=False),
    sa.Column('parameters_json', sqlite.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_control_sequence_instances_instance_id'), 'control_sequence_instances', ['instance_id'], unique=False)
    op.execute("CREATE UNIQUE INDEX ix_unique_active_instance ON control_sequence_instances (instance_id) WHERE is_active = 1")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX ix_unique_active_instance")
    op.drop_index(op.f('ix_control_sequence_instances_instance_id'), table_name='control_sequence_instances')
    op.drop_table('control_sequence_instances')
    # ### end Alembic commands ###
