/* Simulation code for ReheatControllerFMU generated by the OpenModelica Compiler OpenModelica 1.25.7. */
#if !defined(ReheatControllerFMU__MODEL_H)
#define ReheatControllerFMU__MODEL_H

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_json.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "util/parallel_helper.h"
#include "simulation/jacobian_util.h"
#include "simulation/simulation_omc_assert.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"
#include "simulation/solver/spatialDistribution.h"
#include "simulation/solver/synchronous.h"

#if defined(__cplusplus)
extern "C" {
#endif

#include <string.h>

#include "ReheatControllerFMU_functions.h"

#define Buildings_Utilities_Math_Functions_round_index 0

extern void ReheatControllerFMU_callExternalObjectDestructors(DATA *_data, threadData_t *threadData);
#if !defined(OMC_NUM_NONLINEAR_SYSTEMS) || OMC_NUM_NONLINEAR_SYSTEMS>0
#endif
#if !defined(OMC_NUM_LINEAR_SYSTEMS) || OMC_NUM_LINEAR_SYSTEMS>0
#endif
#if !defined(OMC_NUM_MIXED_SYSTEMS) || OMC_NUM_MIXED_SYSTEMS>0
#endif
#if !defined(OMC_NO_STATESELECTION)
extern void ReheatControllerFMU_initializeStateSets(int nStateSets, STATE_SET_DATA* statesetData, DATA *data);
#endif
extern int ReheatControllerFMU_functionAlgebraics(DATA *data, threadData_t *threadData);
extern int ReheatControllerFMU_function_storeDelayed(DATA *data, threadData_t *threadData);
extern int ReheatControllerFMU_function_storeSpatialDistribution(DATA *data, threadData_t *threadData);
extern int ReheatControllerFMU_function_initSpatialDistribution(DATA *data, threadData_t *threadData);
extern int ReheatControllerFMU_updateBoundVariableAttributes(DATA *data, threadData_t *threadData);
extern int ReheatControllerFMU_functionInitialEquations(DATA *data, threadData_t *threadData);
extern int ReheatControllerFMU_functionInitialEquations_lambda0(DATA *data, threadData_t *threadData);
extern int ReheatControllerFMU_functionRemovedInitialEquations(DATA *data, threadData_t *threadData);
extern int ReheatControllerFMU_updateBoundParameters(DATA *data, threadData_t *threadData);
extern int ReheatControllerFMU_checkForAsserts(DATA *data, threadData_t *threadData);
extern int ReheatControllerFMU_function_ZeroCrossingsEquations(DATA *data, threadData_t *threadData);
extern int ReheatControllerFMU_function_ZeroCrossings(DATA *data, threadData_t *threadData, double* gout);
extern int ReheatControllerFMU_function_updateRelations(DATA *data, threadData_t *threadData, int evalZeroCross);
extern const char* ReheatControllerFMU_zeroCrossingDescription(int i, int **out_EquationIndexes);
extern const char* ReheatControllerFMU_relationDescription(int i);
extern void ReheatControllerFMU_function_initSample(DATA *data, threadData_t *threadData);
extern int ReheatControllerFMU_initialAnalyticJacobianG(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int ReheatControllerFMU_initialAnalyticJacobianA(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int ReheatControllerFMU_initialAnalyticJacobianB(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int ReheatControllerFMU_initialAnalyticJacobianC(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int ReheatControllerFMU_initialAnalyticJacobianD(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int ReheatControllerFMU_initialAnalyticJacobianF(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int ReheatControllerFMU_initialAnalyticJacobianH(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int ReheatControllerFMU_functionJacG_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int ReheatControllerFMU_functionJacA_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int ReheatControllerFMU_functionJacB_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int ReheatControllerFMU_functionJacC_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int ReheatControllerFMU_functionJacD_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int ReheatControllerFMU_functionJacF_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int ReheatControllerFMU_functionJacH_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern const char* ReheatControllerFMU_linear_model_frame(void);
extern const char* ReheatControllerFMU_linear_model_datarecovery_frame(void);
extern int ReheatControllerFMU_mayer(DATA* data, modelica_real** res, short *);
extern int ReheatControllerFMU_lagrange(DATA* data, modelica_real** res, short *, short *);
extern int ReheatControllerFMU_pickUpBoundsForInputsInOptimization(DATA* data, modelica_real* min, modelica_real* max, modelica_real*nominal, modelica_boolean *useNominal, char ** name, modelica_real * start, modelica_real * startTimeOpt);
extern int ReheatControllerFMU_setInputData(DATA *data, const modelica_boolean file);
extern int ReheatControllerFMU_getTimeGrid(DATA *data, modelica_integer * nsi, modelica_real**t);
extern void ReheatControllerFMU_function_initSynchronous(DATA * data, threadData_t *threadData);
extern void ReheatControllerFMU_function_updateSynchronous(DATA * data, threadData_t *threadData, long base_idx);
extern int ReheatControllerFMU_function_equationsSynchronous(DATA * data, threadData_t *threadData, long base_idx, long sub_idx);
extern void ReheatControllerFMU_read_simulation_info(SIMULATION_INFO* simulationData);
extern void ReheatControllerFMU_read_input_fmu(MODEL_DATA* modelData);
extern void ReheatControllerFMU_function_savePreSynchronous(DATA *data, threadData_t *threadData);
extern int ReheatControllerFMU_inputNames(DATA* data, char ** names);
extern int ReheatControllerFMU_dataReconciliationInputNames(DATA* data, char ** names);
extern int ReheatControllerFMU_dataReconciliationUnmeasuredVariables(DATA* data, char ** names);
extern int ReheatControllerFMU_initializeDAEmodeData(DATA *data, DAEMODE_DATA*);
extern int ReheatControllerFMU_functionLocalKnownVars(DATA* data, threadData_t* threadData);
extern int ReheatControllerFMU_symbolicInlineSystem(DATA* data, threadData_t* threadData);

#include "ReheatControllerFMU_literals.h"




#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#if defined(__cplusplus)
}
#endif

#endif /* !defined(ReheatControllerFMU__MODEL_H) */


