/* Additional record code for ReheatControllerFMU generated by the OpenModelica Compiler OpenModelica 1.25.7. */

#include "omc_simulation_settings.h"
#include "meta/meta_modelica.h"
#include "ReheatControllerFMU_functions.h"

#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif

