/* Linearization */
#include "ReheatControllerFMU_model.h"
#if defined(__cplusplus)
extern "C" {
#endif
const char *ReheatControllerFMU_linear_model_frame()
{
  return "model linearized_model \"ReheatControllerFMU\"\n"
  "  parameter Integer n = 4 \"number of states\";\n"
  "  parameter Integer m = 17 \"number of inputs\";\n"
  "  parameter Integer p = 15 \"number of outputs\";\n"
  "\n"
  "  parameter Real x0[n] = %s;\n"
  "  parameter Real u0[m] = %s;\n"
  "\n"
  "  parameter Real A[n, n] =\n\t[%s];\n\n"
  "  parameter Real B[n, m] =\n\t[%s];\n\n"
  "  parameter Real C[p, n] =\n\t[%s];\n\n"
  "  parameter Real D[p, m] =\n\t[%s];\n\n"
  "\n"
  "  Real x[n](start=x0);\n"
  "  input Real u[m](start=u0);\n"
  "  output Real y[p];\n"
  "\n"
  "  Real 'x_conLoo.conCoo.I.y' = x[1];\n"
  "  Real 'x_conLoo.conHea.I.y' = x[2];\n"
  "  Real 'x_damVal.conDam.I.y' = x[3];\n"
  "  Real 'x_damVal.conVal.I.y' = x[4];\n"
  "  Real 'u_TCooSet' = u[1];\n"
  "  Real 'u_TDis' = u[2];\n"
  "  Real 'u_THeaSet' = u[3];\n"
  "  Real 'u_TSup' = u[4];\n"
  "  Real 'u_TSupSet' = u[5];\n"
  "  Real 'u_TZon' = u[6];\n"
  "  Real 'u_VDis_flow' = u[7];\n"
  "  Real 'u_oveDamPos' = u[8];\n"
  "  Real 'u_oveFloSet' = u[9];\n"
  "  Real 'u_ppmCO2' = u[10];\n"
  "  Real 'u_ppmCO2Set' = u[11];\n"
  "  Real 'u_u1Fan' = u[12];\n"
  "  Real 'u_u1HotPla' = u[13];\n"
  "  Real 'u_u1Occ' = u[14];\n"
  "  Real 'u_u1Win' = u[15];\n"
  "  Real 'u_uHeaOff' = u[16];\n"
  "  Real 'u_uOpeMod' = u[17];\n"
  "  Real 'y_VAdjAreBreZon_flow' = y[1];\n"
  "  Real 'y_VAdjPopBreZon_flow' = y[2];\n"
  "  Real 'y_VMinOA_flow' = y[3];\n"
  "  Real 'y_VSet_flow' = y[4];\n"
  "  Real 'y_yDam' = y[5];\n"
  "  Real 'y_yFloSenAla' = y[6];\n"
  "  Real 'y_yHeaValResReq' = y[7];\n"
  "  Real 'y_yHotWatPlaReq' = y[8];\n"
  "  Real 'y_yLeaDamAla' = y[9];\n"
  "  Real 'y_yLeaValAla' = y[10];\n"
  "  Real 'y_yLowFloAla' = y[11];\n"
  "  Real 'y_yLowTemAla' = y[12];\n"
  "  Real 'y_yVal' = y[13];\n"
  "  Real 'y_yZonPreResReq' = y[14];\n"
  "  Real 'y_yZonTemResReq' = y[15];\n"
  "equation\n"
  "  der(x) = A * x + B * u;\n"
  "  y = C * x + D * u;\n"
  "end linearized_model;\n";
}
const char *ReheatControllerFMU_linear_model_datarecovery_frame()
{
  return "model linearized_model \"ReheatControllerFMU\"\n"
  "  parameter Integer n = 4 \"number of states\";\n"
  "  parameter Integer m = 17 \"number of inputs\";\n"
  "  parameter Integer p = 15 \"number of outputs\";\n"
  "  parameter Integer nz = 184 \"data recovery variables\";\n"
  "\n"
  "  parameter Real x0[n] = %s;\n"
  "  parameter Real u0[m] = %s;\n"
  "  parameter Real z0[nz] = %s;\n"
  "\n"
  "  parameter Real A[n, n] =\n\t[%s];\n\n"
  "  parameter Real B[n, m] =\n\t[%s];\n\n"
  "  parameter Real C[p, n] =\n\t[%s];\n\n"
  "  parameter Real D[p, m] =\n\t[%s];\n\n"
  "  parameter Real Cz[nz, n] =\n\t[%s];\n\n"
  "  parameter Real Dz[nz, m] =\n\t[%s];\n\n"
  "\n"
  "  Real x[n](start=x0);\n"
  "  input Real u[m](start=u0);\n"
  "  output Real y[p];\n"
  "  output Real z[nz];\n"
  "\n"
  "  Real 'x_conLoo.conCoo.I.y' = x[1];\n"
  "  Real 'x_conLoo.conHea.I.y' = x[2];\n"
  "  Real 'x_damVal.conDam.I.y' = x[3];\n"
  "  Real 'x_damVal.conVal.I.y' = x[4];\n"
  "  Real 'u_TCooSet' = u[1];\n"
  "  Real 'u_TDis' = u[2];\n"
  "  Real 'u_THeaSet' = u[3];\n"
  "  Real 'u_TSup' = u[4];\n"
  "  Real 'u_TSupSet' = u[5];\n"
  "  Real 'u_TZon' = u[6];\n"
  "  Real 'u_VDis_flow' = u[7];\n"
  "  Real 'u_oveDamPos' = u[8];\n"
  "  Real 'u_oveFloSet' = u[9];\n"
  "  Real 'u_ppmCO2' = u[10];\n"
  "  Real 'u_ppmCO2Set' = u[11];\n"
  "  Real 'u_u1Fan' = u[12];\n"
  "  Real 'u_u1HotPla' = u[13];\n"
  "  Real 'u_u1Occ' = u[14];\n"
  "  Real 'u_u1Win' = u[15];\n"
  "  Real 'u_uHeaOff' = u[16];\n"
  "  Real 'u_uOpeMod' = u[17];\n"
  "  Real 'y_VAdjAreBreZon_flow' = y[1];\n"
  "  Real 'y_VAdjPopBreZon_flow' = y[2];\n"
  "  Real 'y_VMinOA_flow' = y[3];\n"
  "  Real 'y_VSet_flow' = y[4];\n"
  "  Real 'y_yDam' = y[5];\n"
  "  Real 'y_yFloSenAla' = y[6];\n"
  "  Real 'y_yHeaValResReq' = y[7];\n"
  "  Real 'y_yHotWatPlaReq' = y[8];\n"
  "  Real 'y_yLeaDamAla' = y[9];\n"
  "  Real 'y_yLeaValAla' = y[10];\n"
  "  Real 'y_yLowFloAla' = y[11];\n"
  "  Real 'y_yLowTemAla' = y[12];\n"
  "  Real 'y_yVal' = y[13];\n"
  "  Real 'y_yZonPreResReq' = y[14];\n"
  "  Real 'y_yZonTemResReq' = y[15];\n"
  "  Real 'z_$cse1' = z[1];\n"
  "  Real 'z_$cse2' = z[2];\n"
  "  Real 'z_$cse3' = z[3];\n"
  "  Real 'z_$cse4' = z[4];\n"
  "  Real 'z_$cse5' = z[5];\n"
  "  Real 'z_TCooSet' = z[6];\n"
  "  Real 'z_TDis' = z[7];\n"
  "  Real 'z_THeaSet' = z[8];\n"
  "  Real 'z_TSup' = z[9];\n"
  "  Real 'z_TSupSet' = z[10];\n"
  "  Real 'z_TZon' = z[11];\n"
  "  Real 'z_VAdjAreBreZon_flow' = z[12];\n"
  "  Real 'z_VAdjPopBreZon_flow' = z[13];\n"
  "  Real 'z_VDis_flow' = z[14];\n"
  "  Real 'z_VMinOA_flow' = z[15];\n"
  "  Real 'z_VSet_flow' = z[16];\n"
  "  Real 'z_actAirSet.VActCooMax_flow' = z[17];\n"
  "  Real 'z_actAirSet.VActHeaMax_flow' = z[18];\n"
  "  Real 'z_actAirSet.VActHeaMin_flow' = z[19];\n"
  "  Real 'z_actAirSet.VActMin_flow' = z[20];\n"
  "  Real 'z_actAirSet.add2.y' = z[21];\n"
  "  Real 'z_actAirSet.add3.y' = z[22];\n"
  "  Real 'z_actAirSet.cooMaxFlo.y' = z[23];\n"
  "  Real 'z_actAirSet.heaMaxFlo.y' = z[24];\n"
  "  Real 'z_actAirSet.heaMaxFlo1.y' = z[25];\n"
  "  Real 'z_actAirSet.heaMinFlo.y' = z[26];\n"
  "  Real 'z_actAirSet.max1.y' = z[27];\n"
  "  Real 'z_actAirSet.max2.y' = z[28];\n"
  "  Real 'z_actAirSet.occModInd.y' = z[29];\n"
  "  Real 'z_actAirSet.pro1.y' = z[30];\n"
  "  Real 'z_actAirSet.pro2.y' = z[31];\n"
  "  Real 'z_ala.addPar.y' = z[32];\n"
  "  Real 'z_ala.addPar1.y' = z[33];\n"
  "  Real 'z_ala.addPar2.y' = z[34];\n"
  "  Real 'z_ala.gai.y' = z[35];\n"
  "  Real 'z_ala.gai1.y' = z[36];\n"
  "  Real 'z_ala.gai2.y' = z[37];\n"
  "  Real 'z_conLoo.conCoo.Dzero.y' = z[38];\n"
  "  Real 'z_conLoo.conCoo.I.u' = z[39];\n"
  "  Real 'z_conLoo.conCoo.P.u' = z[40];\n"
  "  Real 'z_conLoo.conCoo.addPD.y' = z[41];\n"
  "  Real 'z_conLoo.conCoo.addPID.y' = z[42];\n"
  "  Real 'z_conLoo.conCoo.addRes.y' = z[43];\n"
  "  Real 'z_conLoo.conCoo.antWinErr.y' = z[44];\n"
  "  Real 'z_conLoo.conCoo.antWinGai.y' = z[45];\n"
  "  Real 'z_conLoo.conCoo.controlError.y' = z[46];\n"
  "  Real 'z_conLoo.conCoo.errI1.y' = z[47];\n"
  "  Real 'z_conLoo.conCoo.errP.u1' = z[48];\n"
  "  Real 'z_conLoo.conCoo.uMea_revAct.y' = z[49];\n"
  "  Real 'z_conLoo.conCoo.y' = z[50];\n"
  "  Real 'z_conLoo.conHea.Dzero.y' = z[51];\n"
  "  Real 'z_conLoo.conHea.I.u' = z[52];\n"
  "  Real 'z_conLoo.conHea.P.u' = z[53];\n"
  "  Real 'z_conLoo.conHea.addPD.y' = z[54];\n"
  "  Real 'z_conLoo.conHea.addPID.y' = z[55];\n"
  "  Real 'z_conLoo.conHea.addRes.y' = z[56];\n"
  "  Real 'z_conLoo.conHea.antWinErr.y' = z[57];\n"
  "  Real 'z_conLoo.conHea.antWinGai.y' = z[58];\n"
  "  Real 'z_conLoo.conHea.controlError.y' = z[59];\n"
  "  Real 'z_conLoo.conHea.errI1.y' = z[60];\n"
  "  Real 'z_conLoo.conHea.errP.u1' = z[61];\n"
  "  Real 'z_conLoo.conHea.uMea_revAct.y' = z[62];\n"
  "  Real 'z_conLoo.conHea.y' = z[63];\n"
  "  Real 'z_conLoo.yCoo' = z[64];\n"
  "  Real 'z_conLoo.yHea' = z[65];\n"
  "  Real 'z_conLoo.zerCoo.y' = z[66];\n"
  "  Real 'z_conLoo.zerHea.y' = z[67];\n"
  "  Real 'z_damVal.TDisSet' = z[68];\n"
  "  Real 'z_damVal.VDisSet_flowNor.y' = z[69];\n"
  "  Real 'z_damVal.VDis_flowNor.y' = z[70];\n"
  "  Real 'z_damVal.add1.y' = z[71];\n"
  "  Real 'z_damVal.add2.y' = z[72];\n"
  "  Real 'z_damVal.add4.y' = z[73];\n"
  "  Real 'z_damVal.addPar.y' = z[74];\n"
  "  Real 'z_damVal.addPar1.y' = z[75];\n"
  "  Real 'z_damVal.conDam.Dzero.y' = z[76];\n"
  "  Real 'z_damVal.conDam.I.u' = z[77];\n"
  "  Real 'z_damVal.conDam.P.u' = z[78];\n"
  "  Real 'z_damVal.conDam.addPD.y' = z[79];\n"
  "  Real 'z_damVal.conDam.addPID.y' = z[80];\n"
  "  Real 'z_damVal.conDam.addRes.y' = z[81];\n"
  "  Real 'z_damVal.conDam.antWinErr.y' = z[82];\n"
  "  Real 'z_damVal.conDam.antWinGai.y' = z[83];\n"
  "  Real 'z_damVal.conDam.controlError.y' = z[84];\n"
  "  Real 'z_damVal.conDam.errI1.y' = z[85];\n"
  "  Real 'z_damVal.conDam.errP.u1' = z[86];\n"
  "  Real 'z_damVal.conDam.uMea_revAct.y' = z[87];\n"
  "  Real 'z_damVal.conDam.y' = z[88];\n"
  "  Real 'z_damVal.conHal.y' = z[89];\n"
  "  Real 'z_damVal.conHal1.y' = z[90];\n"
  "  Real 'z_damVal.conOne.y' = z[91];\n"
  "  Real 'z_damVal.conOne2.y' = z[92];\n"
  "  Real 'z_damVal.conTDisHeaSet.a' = z[93];\n"
  "  Real 'z_damVal.conTDisHeaSet.b' = z[94];\n"
  "  Real 'z_damVal.conTDisHeaSet.xLim' = z[95];\n"
  "  Real 'z_damVal.conTDisHeaSet.y' = z[96];\n"
  "  Real 'z_damVal.conVal.Dzero.y' = z[97];\n"
  "  Real 'z_damVal.conVal.I.u' = z[98];\n"
  "  Real 'z_damVal.conVal.P.u' = z[99];\n"
  "  Real 'z_damVal.conVal.addPD.y' = z[100];\n"
  "  Real 'z_damVal.conVal.addPID.y' = z[101];\n"
  "  Real 'z_damVal.conVal.addRes.y' = z[102];\n"
  "  Real 'z_damVal.conVal.antWinErr.y' = z[103];\n"
  "  Real 'z_damVal.conVal.antWinGai.y' = z[104];\n"
  "  Real 'z_damVal.conVal.controlError.y' = z[105];\n"
  "  Real 'z_damVal.conVal.errI1.y' = z[106];\n"
  "  Real 'z_damVal.conVal.errP.u1' = z[107];\n"
  "  Real 'z_damVal.conVal.uMea_revAct.y' = z[108];\n"
  "  Real 'z_damVal.conVal.y' = z[109];\n"
  "  Real 'z_damVal.conZer.y' = z[110];\n"
  "  Real 'z_damVal.conZer2.y' = z[111];\n"
  "  Real 'z_damVal.conZer3.y' = z[112];\n"
  "  Real 'z_damVal.cooMax.y' = z[113];\n"
  "  Real 'z_damVal.heaMax.y' = z[114];\n"
  "  Real 'z_damVal.lin.a' = z[115];\n"
  "  Real 'z_damVal.lin.b' = z[116];\n"
  "  Real 'z_damVal.lin.xLim' = z[117];\n"
  "  Real 'z_damVal.lin.y' = z[118];\n"
  "  Real 'z_damVal.lin3.a' = z[119];\n"
  "  Real 'z_damVal.lin3.b' = z[120];\n"
  "  Real 'z_damVal.lin3.xLim' = z[121];\n"
  "  Real 'z_damVal.lin3.y' = z[122];\n"
  "  Real 'z_damVal.max1.y' = z[123];\n"
  "  Real 'z_damVal.max2.y' = z[124];\n"
  "  Real 'z_damVal.minFlo.y' = z[125];\n"
  "  Real 'z_damVal.sub2.y' = z[126];\n"
  "  Real 'z_damVal.swi.y' = z[127];\n"
  "  Real 'z_damVal.swi1.y' = z[128];\n"
  "  Real 'z_damVal.swi2.y' = z[129];\n"
  "  Real 'z_damVal.swi4.y' = z[130];\n"
  "  Real 'z_damVal.swi5.y' = z[131];\n"
  "  Real 'z_damVal.yDam' = z[132];\n"
  "  Real 'z_damVal.yVal' = z[133];\n"
  "  Real 'z_damVal.zerFlo.y' = z[134];\n"
  "  Real 'z_ppmCO2' = z[135];\n"
  "  Real 'z_ppmCO2Set' = z[136];\n"
  "  Real 'z_setOve.add3.y' = z[137];\n"
  "  Real 'z_setOve.booToRea.y' = z[138];\n"
  "  Real 'z_setOve.cloDam.y' = z[139];\n"
  "  Real 'z_setOve.opeDam.y' = z[140];\n"
  "  Real 'z_setPoi.VOccZonMin_flow' = z[141];\n"
  "  Real 'z_setPoi.addPar.y' = z[142];\n"
  "  Real 'z_setPoi.airDisEff.y' = z[143];\n"
  "  Real 'z_setPoi.booToRea.y' = z[144];\n"
  "  Real 'z_setPoi.booToRea1.y' = z[145];\n"
  "  Real 'z_setPoi.co2Con.y' = z[146];\n"
  "  Real 'z_setPoi.lin.a' = z[147];\n"
  "  Real 'z_setPoi.lin.b' = z[148];\n"
  "  Real 'z_setPoi.lin.xLim' = z[149];\n"
  "  Real 'z_setPoi.lin.y' = z[150];\n"
  "  Real 'z_setPoi.occMinAirSet.a' = z[151];\n"
  "  Real 'z_setPoi.occMinAirSet.b' = z[152];\n"
  "  Real 'z_setPoi.occMinAirSet.xLim' = z[153];\n"
  "  Real 'z_setPoi.occMinAirSet.y' = z[154];\n"
  "  Real 'z_setPoi.one.y' = z[155];\n"
  "  Real 'z_setPoi.popBreOutAir.a' = z[156];\n"
  "  Real 'z_setPoi.popBreOutAir.xLim' = z[157];\n"
  "  Real 'z_setPoi.popBreOutAir.y' = z[158];\n"
  "  Real 'z_setPoi.reqBreAir.y' = z[159];\n"
  "  Real 'z_setPoi.unPopAreBreAir.y' = z[160];\n"
  "  Real 'z_setPoi.unpAreBreAir.y' = z[161];\n"
  "  Real 'z_setPoi.unpMinZonAir.y' = z[162];\n"
  "  Real 'z_setPoi.unpMinZonFlo.y' = z[163];\n"
  "  Real 'z_setPoi.unpPopBreAir.y' = z[164];\n"
  "  Real 'z_setPoi.zer.y' = z[165];\n"
  "  Real 'z_setPoi.zer1.y' = z[166];\n"
  "  Real 'z_setPoi.zonMinFlo.y' = z[167];\n"
  "  Real 'z_sysReq.addPar.y' = z[168];\n"
  "  Real 'z_sysReq.addPar1.y' = z[169];\n"
  "  Real 'z_sysReq.gai2.y' = z[170];\n"
  "  Real 'z_sysReq.greEqu.u1' = z[171];\n"
  "  Real 'z_sysReq.sub2.y' = z[172];\n"
  "  Real 'z_sysReq.sub3.y' = z[173];\n"
  "  Real 'z_timSup.abs1.y' = z[174];\n"
  "  Real 'z_timSup.abs2.y' = z[175];\n"
  "  Real 'z_timSup.conZer.y' = z[176];\n"
  "  Real 'z_timSup.gai.y' = z[177];\n"
  "  Real 'z_timSup.sub1.y' = z[178];\n"
  "  Real 'z_timSup.supTim.y' = z[179];\n"
  "  Real 'z_timSup.swi.y' = z[180];\n"
  "  Real 'z_timSup.temDif.y' = z[181];\n"
  "  Real 'z_timSup.tim.y' = z[182];\n"
  "  Real 'z_yDam' = z[183];\n"
  "  Real 'z_yVal' = z[184];\n"
  "equation\n"
  "  der(x) = A * x + B * u;\n"
  "  y = C * x + D * u;\n"
  "  z = Cz * x + Dz * u;\n"
  "end linearized_model;\n";
}
#if defined(__cplusplus)
}
#endif
